
-- 키즈카페방문이력
CREATE TABLE CAFE_VISITING_RECORD
(
	CHILD_ID       varchar(50) NOT NULL, -- 자녀ID
	START_TIME     date        NOT NULL, -- 입장시간
	BAND_DEVICE_ID varchar(50) NULL,     -- 밴드디바이스ID
	END_TIME       date        NULL,     -- 퇴장시간
	AMOUNT_PRICE   integer     NULL,     -- 청구금액
	USING_TIME     integer     NULL      -- 이용시간
);

-- 키즈카페방문이력
COMMENT ON TABLE CAFE_VISITING_RECORD IS '키즈카페방문이력';

-- 자녀ID
COMMENT ON COLUMN CAFE_VISITING_RECORD.CHILD_ID IS '자녀ID';

-- 입장시간
COMMENT ON COLUMN CAFE_VISITING_RECORD.START_TIME IS '입장시간';

-- 밴드디바이스ID
COMMENT ON COLUMN CAFE_VISITING_RECORD.BAND_DEVICE_ID IS '밴드디바이스ID';

-- 퇴장시간
COMMENT ON COLUMN CAFE_VISITING_RECORD.END_TIME IS '퇴장시간';

-- 청구금액
COMMENT ON COLUMN CAFE_VISITING_RECORD.AMOUNT_PRICE IS '청구금액';

-- 이용시간
COMMENT ON COLUMN CAFE_VISITING_RECORD.USING_TIME IS '이용시간';

-- 키즈카페방문이력 기본키
CREATE UNIQUE INDEX PK_CAFE_VISITING_RECORD
	ON CAFE_VISITING_RECORD
	( -- 키즈카페방문이력
		CHILD_ID ASC, -- 자녀ID
		START_TIME ASC -- 입장시간
	)
;
-- 키즈카페방문이력
ALTER TABLE CAFE_VISITING_RECORD
	ADD CONSTRAINT PK_CAFE_VISITING_RECORD
		 -- 키즈카페방문이력 기본키
	PRIMARY KEY 
	USING INDEX PK_CAFE_VISITING_RECORD;

-- 키즈카페방문이력 기본키
COMMENT ON CONSTRAINT PK_CAFE_VISITING_RECORD ON CAFE_VISITING_RECORD IS '키즈카페방문이력 기본키';

-- 자녀
CREATE TABLE K_CHILD
(
	ID                     varchar(50) NOT NULL, -- ID
	USER_ID                varchar(50) NULL,     -- 회원ID
	NAME                   varchar(50) NULL,     -- 이름
	TARGET_ACTIVITY_FIGURE integer     NULL,     -- 목표활동량
	AGE                    integer     NULL,     -- 나이
	HEIGHT                 integer     NULL,     -- 신장
	WEIGHT                 integer     NULL,     -- 몸무게
	SEX                    varchar(10) NULL,     -- 성별
	IS_BAND_WEARING        boolean     NULL      -- 밴드디바이스착용여부
);

-- 자녀
COMMENT ON TABLE K_CHILD IS '자녀';

-- ID
COMMENT ON COLUMN K_CHILD.ID IS 'ID';

-- 회원ID
COMMENT ON COLUMN K_CHILD.USER_ID IS '회원ID';

-- 이름
COMMENT ON COLUMN K_CHILD.NAME IS '이름';

-- 목표활동량
COMMENT ON COLUMN K_CHILD.TARGET_ACTIVITY_FIGURE IS '목표활동량';

-- 나이
COMMENT ON COLUMN K_CHILD.AGE IS '나이';

-- 신장
COMMENT ON COLUMN K_CHILD.HEIGHT IS '신장';

-- 몸무게
COMMENT ON COLUMN K_CHILD.WEIGHT IS '몸무게';

-- 성별
COMMENT ON COLUMN K_CHILD.SEX IS '성별';

-- 밴드디바이스착용여부
COMMENT ON COLUMN K_CHILD.IS_BAND_WEARING IS '밴드디바이스착용여부';

-- 자녀 기본키
CREATE UNIQUE INDEX PK_K_CHILD
	ON K_CHILD
	( -- 자녀
		ID ASC -- ID
	)
;
-- 자녀
ALTER TABLE K_CHILD
	ADD CONSTRAINT PK_K_CHILD
		 -- 자녀 기본키
	PRIMARY KEY 
	USING INDEX PK_K_CHILD;

-- 자녀 기본키
COMMENT ON CONSTRAINT PK_K_CHILD ON K_CHILD IS '자녀 기본키';

-- 키즈카페매출일통계
CREATE TABLE CAFE_INCOME_DAILY_STATISTICS
(
	DATE    date    NOT NULL, -- 일시
	AVERAGE integer NULL,     -- 평균매출
	MAXIMUM integer NULL,     -- 최대매출
	MINIMUM integer NULL      -- 최소매출
);

-- 키즈카페매출일통계
COMMENT ON TABLE CAFE_INCOME_DAILY_STATISTICS IS '키즈카페매출일통계';

-- 일시
COMMENT ON COLUMN CAFE_INCOME_DAILY_STATISTICS.DATE IS '일시';

-- 평균매출
COMMENT ON COLUMN CAFE_INCOME_DAILY_STATISTICS.AVERAGE IS '평균매출';

-- 최대매출
COMMENT ON COLUMN CAFE_INCOME_DAILY_STATISTICS.MAXIMUM IS '최대매출';

-- 최소매출
COMMENT ON COLUMN CAFE_INCOME_DAILY_STATISTICS.MINIMUM IS '최소매출';

-- 키즈카페매출일통계 기본키
CREATE UNIQUE INDEX PK_CAFE_INCOME_DAILY_STATISTICS
	ON CAFE_INCOME_DAILY_STATISTICS
	( -- 키즈카페매출일통계
		DATE ASC -- 일시
	)
;
-- 키즈카페매출일통계
ALTER TABLE CAFE_INCOME_DAILY_STATISTICS
	ADD CONSTRAINT PK_CAFE_INCOME_DAILY_STATISTICS
		 -- 키즈카페매출일통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CAFE_INCOME_DAILY_STATISTICS;

-- 키즈카페매출일통계 기본키
COMMENT ON CONSTRAINT PK_CAFE_INCOME_DAILY_STATISTICS ON CAFE_INCOME_DAILY_STATISTICS IS '키즈카페매출일통계 기본키';

-- 자녀놀이구역방문시통계
CREATE TABLE CHILD_ZONE_VISITING_HOUR_STATISTICS
(
	CHILD_ID varchar(50) NOT NULL, -- 자녀ID
	ZONE_ID  varchar(50) NOT NULL, -- 놀이구역ID
	DATE     date        NOT NULL, -- 일시
	AVERAGE  integer     NOT NULL  -- 평균방문횟수
);

-- 자녀놀이구역방문시통계
COMMENT ON TABLE CHILD_ZONE_VISITING_HOUR_STATISTICS IS '자녀놀이구역방문시통계';

-- 자녀ID
COMMENT ON COLUMN CHILD_ZONE_VISITING_HOUR_STATISTICS.CHILD_ID IS '자녀ID';

-- 놀이구역ID
COMMENT ON COLUMN CHILD_ZONE_VISITING_HOUR_STATISTICS.ZONE_ID IS '놀이구역ID';

-- 일시
COMMENT ON COLUMN CHILD_ZONE_VISITING_HOUR_STATISTICS.DATE IS '일시';

-- 평균방문횟수
COMMENT ON COLUMN CHILD_ZONE_VISITING_HOUR_STATISTICS.AVERAGE IS '평균방문횟수';

-- 자녀놀이구역방문시통계 기본키
CREATE UNIQUE INDEX PK_CHILD_ZONE_VISITING_HOUR_STATISTICS
	ON CHILD_ZONE_VISITING_HOUR_STATISTICS
	( -- 자녀놀이구역방문시통계
		CHILD_ID ASC, -- 자녀ID
		ZONE_ID ASC, -- 놀이구역ID
		DATE ASC -- 일시
	)
;
-- 자녀놀이구역방문시통계
ALTER TABLE CHILD_ZONE_VISITING_HOUR_STATISTICS
	ADD CONSTRAINT PK_CHILD_ZONE_VISITING_HOUR_STATISTICS
		 -- 자녀놀이구역방문시통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CHILD_ZONE_VISITING_HOUR_STATISTICS;

-- 자녀놀이구역방문시통계 기본키
COMMENT ON CONSTRAINT PK_CHILD_ZONE_VISITING_HOUR_STATISTICS ON CHILD_ZONE_VISITING_HOUR_STATISTICS IS '자녀놀이구역방문시통계 기본키';

-- BMR
CREATE TABLE BMR
(
	AGE     integer     NOT NULL, -- 나이
	SEX     varchar(10) NOT NULL, -- 성별
	CALORIE integer     NULL      -- 권장칼로리
);

-- BMR
COMMENT ON TABLE BMR IS 'BMR';

-- 나이
COMMENT ON COLUMN BMR.AGE IS '나이';

-- 성별
COMMENT ON COLUMN BMR.SEX IS '성별';

-- 권장칼로리
COMMENT ON COLUMN BMR.CALORIE IS '권장칼로리';

-- BMR 기본키
CREATE UNIQUE INDEX PK_BMR
	ON BMR
	( -- BMR
		AGE ASC, -- 나이
		SEX ASC -- 성별
	)
;
-- BMR
ALTER TABLE BMR
	ADD CONSTRAINT PK_BMR
		 -- BMR 기본키
	PRIMARY KEY 
	USING INDEX PK_BMR;

-- BMR 기본키
COMMENT ON CONSTRAINT PK_BMR ON BMR IS 'BMR 기본키';

-- 자녀활동량시통계
CREATE TABLE CHILD_ACTIVITY_DAILY_STATISTICS
(
	CHILD_ID varchar(50) NOT NULL, -- 자녀ID
	DATE     date        NOT NULL, -- 일시
	AVERAGE  integer     NULL,     -- 평균활동량
	MAXIMUM  integer     NULL,     -- 최대활동량
	MINIMUM  integer     NULL      -- 최소활동량
);

-- 자녀활동량시통계
COMMENT ON TABLE CHILD_ACTIVITY_DAILY_STATISTICS IS '자녀활동량시통계';

-- 자녀ID
COMMENT ON COLUMN CHILD_ACTIVITY_DAILY_STATISTICS.CHILD_ID IS '자녀ID';

-- 일시
COMMENT ON COLUMN CHILD_ACTIVITY_DAILY_STATISTICS.DATE IS '일시';

-- 평균활동량
COMMENT ON COLUMN CHILD_ACTIVITY_DAILY_STATISTICS.AVERAGE IS '평균활동량';

-- 최대활동량
COMMENT ON COLUMN CHILD_ACTIVITY_DAILY_STATISTICS.MAXIMUM IS '최대활동량';

-- 최소활동량
COMMENT ON COLUMN CHILD_ACTIVITY_DAILY_STATISTICS.MINIMUM IS '최소활동량';

-- 자녀활동량시통계 기본키
CREATE UNIQUE INDEX PK_CHILD_ACTIVITY_DAILY_STATISTICS
	ON CHILD_ACTIVITY_DAILY_STATISTICS
	( -- 자녀활동량시통계
		CHILD_ID ASC, -- 자녀ID
		DATE ASC -- 일시
	)
;
-- 자녀활동량시통계
ALTER TABLE CHILD_ACTIVITY_DAILY_STATISTICS
	ADD CONSTRAINT PK_CHILD_ACTIVITY_DAILY_STATISTICS
		 -- 자녀활동량시통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CHILD_ACTIVITY_DAILY_STATISTICS;

-- 자녀활동량시통계 기본키
COMMENT ON CONSTRAINT PK_CHILD_ACTIVITY_DAILY_STATISTICS ON CHILD_ACTIVITY_DAILY_STATISTICS IS '자녀활동량시통계 기본키';

-- 밴드디바이스
CREATE TABLE BAND_DEVICE
(
	ID               varchar(50) NOT NULL, -- ID
	IS_RENT          boolean     NULL,     -- 대여여부
	CURRENT_LOCATION varchar(50) NULL,     -- 현재위치
	BEFORE_LOCATION  varchar(50) NULL      -- 이전위치
);

-- 밴드디바이스
COMMENT ON TABLE BAND_DEVICE IS '밴드디바이스';

-- ID
COMMENT ON COLUMN BAND_DEVICE.ID IS 'ID';

-- 대여여부
COMMENT ON COLUMN BAND_DEVICE.IS_RENT IS '대여여부';

-- 현재위치
COMMENT ON COLUMN BAND_DEVICE.CURRENT_LOCATION IS '현재위치';

-- 이전위치
COMMENT ON COLUMN BAND_DEVICE.BEFORE_LOCATION IS '이전위치';

-- 밴드디바이스 기본키
CREATE UNIQUE INDEX PK_BAND_DEVICE
	ON BAND_DEVICE
	( -- 밴드디바이스
		ID ASC -- ID
	)
;
-- 밴드디바이스
ALTER TABLE BAND_DEVICE
	ADD CONSTRAINT PK_BAND_DEVICE
		 -- 밴드디바이스 기본키
	PRIMARY KEY 
	USING INDEX PK_BAND_DEVICE;

-- 밴드디바이스 기본키
COMMENT ON CONSTRAINT PK_BAND_DEVICE ON BAND_DEVICE IS '밴드디바이스 기본키';

-- 자녀섭취가능음식
CREATE TABLE CHILD_EATABLE
(
	CHILD_ID varchar(50) NOT NULL, -- 자녀ID
	FOOD_ID  varchar(50) NOT NULL  -- 음식ID
);

-- 자녀섭취가능음식
COMMENT ON TABLE CHILD_EATABLE IS '자녀섭취가능음식';

-- 자녀ID
COMMENT ON COLUMN CHILD_EATABLE.CHILD_ID IS '자녀ID';

-- 음식ID
COMMENT ON COLUMN CHILD_EATABLE.FOOD_ID IS '음식ID';

-- 자녀섭취가능음식 기본키
CREATE UNIQUE INDEX PK_CHILD_EATABLE
	ON CHILD_EATABLE
	( -- 자녀섭취가능음식
		CHILD_ID ASC, -- 자녀ID
		FOOD_ID ASC -- 음식ID
	)
;
-- 자녀섭취가능음식
ALTER TABLE CHILD_EATABLE
	ADD CONSTRAINT PK_CHILD_EATABLE
		 -- 자녀섭취가능음식 기본키
	PRIMARY KEY 
	USING INDEX PK_CHILD_EATABLE;

-- 자녀섭취가능음식 기본키
COMMENT ON CONSTRAINT PK_CHILD_EATABLE ON CHILD_EATABLE IS '자녀섭취가능음식 기본키';

-- 놀이구역방문일통계
CREATE TABLE ZONE_VISITING_DAY_STATISTICS
(
	ZONE_ID varchar(50) NOT NULL, -- 놀이구역ID
	AGE     integer     NOT NULL, -- 나이
	DATE    date        NOT NULL, -- 일시
	AVERAGE integer     NULL,     -- 평균방문횟수
	MINIMUM integer     NULL,     -- 최소방문횟수
	MAXIMUM integer     NULL      -- 최대방문횟수
);

-- 놀이구역방문일통계
COMMENT ON TABLE ZONE_VISITING_DAY_STATISTICS IS '놀이구역방문일통계';

-- 놀이구역ID
COMMENT ON COLUMN ZONE_VISITING_DAY_STATISTICS.ZONE_ID IS '놀이구역ID';

-- 나이
COMMENT ON COLUMN ZONE_VISITING_DAY_STATISTICS.AGE IS '나이';

-- 일시
COMMENT ON COLUMN ZONE_VISITING_DAY_STATISTICS.DATE IS '일시';

-- 평균방문횟수
COMMENT ON COLUMN ZONE_VISITING_DAY_STATISTICS.AVERAGE IS '평균방문횟수';

-- 최소방문횟수
COMMENT ON COLUMN ZONE_VISITING_DAY_STATISTICS.MINIMUM IS '최소방문횟수';

-- 최대방문횟수
COMMENT ON COLUMN ZONE_VISITING_DAY_STATISTICS.MAXIMUM IS '최대방문횟수';

-- 놀이구역방문일통계 기본키
CREATE UNIQUE INDEX PK_ZONE_VISITING_DAY_STATISTICS
	ON ZONE_VISITING_DAY_STATISTICS
	( -- 놀이구역방문일통계
		ZONE_ID ASC, -- 놀이구역ID
		AGE ASC, -- 나이
		DATE ASC -- 일시
	)
;
-- 놀이구역방문일통계
ALTER TABLE ZONE_VISITING_DAY_STATISTICS
	ADD CONSTRAINT PK_ZONE_VISITING_DAY_STATISTICS
		 -- 놀이구역방문일통계 기본키
	PRIMARY KEY 
	USING INDEX PK_ZONE_VISITING_DAY_STATISTICS;

-- 놀이구역방문일통계 기본키
COMMENT ON CONSTRAINT PK_ZONE_VISITING_DAY_STATISTICS ON ZONE_VISITING_DAY_STATISTICS IS '놀이구역방문일통계 기본키';

-- 회원
CREATE TABLE K_USER
(
	ID           varchar(50)  NOT NULL, -- ID
	NAME         varchar(50)  NULL,     -- 이름
	PASSWORD     varchar(50)  NULL,     -- 비밀번호
	IS_AUTHOR    boolean      NULL,     -- 관리자여부
	PHONE_NUMBER varchar(50)  NULL,     -- 전화번호
	TOKEN        varchar(200) NULL      -- TOKEN
);

-- 회원
COMMENT ON TABLE K_USER IS '회원';

-- ID
COMMENT ON COLUMN K_USER.ID IS 'ID';

-- 이름
COMMENT ON COLUMN K_USER.NAME IS '이름';

-- 비밀번호
COMMENT ON COLUMN K_USER.PASSWORD IS '비밀번호';

-- 관리자여부
COMMENT ON COLUMN K_USER.IS_AUTHOR IS '관리자여부';

-- 전화번호
COMMENT ON COLUMN K_USER.PHONE_NUMBER IS '전화번호';

-- TOKEN
COMMENT ON COLUMN K_USER.TOKEN IS 'TOKEN';

-- 회원 기본키
CREATE UNIQUE INDEX PK_K_USER
	ON K_USER
	( -- 회원
		ID ASC -- ID
	)
;
-- 회원
ALTER TABLE K_USER
	ADD CONSTRAINT PK_K_USER
		 -- 회원 기본키
	PRIMARY KEY 
	USING INDEX PK_K_USER;

-- 회원 기본키
COMMENT ON CONSTRAINT PK_K_USER ON K_USER IS '회원 기본키';

-- 키즈카페이용시통계
CREATE TABLE CAFE_USAGE_HOUR_STATISTICS
(
	DATE    date    NOT NULL, -- 일시
	AGE     integer NOT NULL, -- 연령
	AVERAGE integer NULL,     -- 평균고객수
	MAXIMUM integer NULL,     -- 최대고객수
	MINIMUM integer NULL      -- 최소고객수
);

-- 키즈카페이용시통계
COMMENT ON TABLE CAFE_USAGE_HOUR_STATISTICS IS '키즈카페이용시통계';

-- 일시
COMMENT ON COLUMN CAFE_USAGE_HOUR_STATISTICS.DATE IS '일시';

-- 연령
COMMENT ON COLUMN CAFE_USAGE_HOUR_STATISTICS.AGE IS '연령';

-- 평균고객수
COMMENT ON COLUMN CAFE_USAGE_HOUR_STATISTICS.AVERAGE IS '평균고객수';

-- 최대고객수
COMMENT ON COLUMN CAFE_USAGE_HOUR_STATISTICS.MAXIMUM IS '최대고객수';

-- 최소고객수
COMMENT ON COLUMN CAFE_USAGE_HOUR_STATISTICS.MINIMUM IS '최소고객수';

-- 키즈카페이용시통계 기본키
CREATE UNIQUE INDEX PK_CAFE_USAGE_HOUR_STATISTICS
	ON CAFE_USAGE_HOUR_STATISTICS
	( -- 키즈카페이용시통계
		DATE ASC, -- 일시
		AGE ASC -- 연령
	)
;
-- 키즈카페이용시통계
ALTER TABLE CAFE_USAGE_HOUR_STATISTICS
	ADD CONSTRAINT PK_CAFE_USAGE_HOUR_STATISTICS
		 -- 키즈카페이용시통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CAFE_USAGE_HOUR_STATISTICS;

-- 키즈카페이용시통계 기본키
COMMENT ON CONSTRAINT PK_CAFE_USAGE_HOUR_STATISTICS ON CAFE_USAGE_HOUR_STATISTICS IS '키즈카페이용시통계 기본키';

-- 가격
CREATE TABLE PRICE
(
	USING_TIME integer NOT NULL, -- 이용시간
	PRICE      integer NULL      -- 가격
);

-- 가격
COMMENT ON TABLE PRICE IS '가격';

-- 이용시간
COMMENT ON COLUMN PRICE.USING_TIME IS '이용시간';

-- 가격
COMMENT ON COLUMN PRICE.PRICE IS '가격';

-- 가격 기본키
CREATE UNIQUE INDEX PK_PRICE
	ON PRICE
	( -- 가격
		USING_TIME ASC -- 이용시간
	)
;
-- 가격
ALTER TABLE PRICE
	ADD CONSTRAINT PK_PRICE
		 -- 가격 기본키
	PRIMARY KEY 
	USING INDEX PK_PRICE;

-- 가격 기본키
COMMENT ON CONSTRAINT PK_PRICE ON PRICE IS '가격 기본키';

-- 자녀심박수10분통계
CREATE TABLE CHILD_PULSE_10M_STATISTICS
(
	CHILD_ID varchar(50) NOT NULL, -- 자녀ID
	DATE     date        NOT NULL, -- 일시
	AVERAGE  integer     NULL,     -- 평균심박수
	MAXIMUM  integer     NULL,     -- 최대심박수
	MINIMUM  integer     NULL      -- 최소심박수
);

-- 자녀심박수10분통계
COMMENT ON TABLE CHILD_PULSE_10M_STATISTICS IS '자녀심박수10분통계';

-- 자녀ID
COMMENT ON COLUMN CHILD_PULSE_10M_STATISTICS.CHILD_ID IS '자녀ID';

-- 일시
COMMENT ON COLUMN CHILD_PULSE_10M_STATISTICS.DATE IS '일시';

-- 평균심박수
COMMENT ON COLUMN CHILD_PULSE_10M_STATISTICS.AVERAGE IS '평균심박수';

-- 최대심박수
COMMENT ON COLUMN CHILD_PULSE_10M_STATISTICS.MAXIMUM IS '최대심박수';

-- 최소심박수
COMMENT ON COLUMN CHILD_PULSE_10M_STATISTICS.MINIMUM IS '최소심박수';

-- 자녀심박수10분통계 기본키
CREATE UNIQUE INDEX PK_CHILD_PULSE_10M_STATISTICS
	ON CHILD_PULSE_10M_STATISTICS
	( -- 자녀심박수10분통계
		CHILD_ID ASC, -- 자녀ID
		DATE ASC -- 일시
	)
;
-- 자녀심박수10분통계
ALTER TABLE CHILD_PULSE_10M_STATISTICS
	ADD CONSTRAINT PK_CHILD_PULSE_10M_STATISTICS
		 -- 자녀심박수10분통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CHILD_PULSE_10M_STATISTICS;

-- 자녀심박수10분통계 기본키
COMMENT ON CONSTRAINT PK_CHILD_PULSE_10M_STATISTICS ON CHILD_PULSE_10M_STATISTICS IS '자녀심박수10분통계 기본키';

-- 놀이구역좌표
CREATE TABLE ZONE_COORDINATE
(
	ZONE_ID      varchar(50) NULL, -- 놀이구역ID
	X_COORDINATE integer     NULL, -- X좌표
	Y_COORDINATE integer     NULL  -- Y좌표
);

-- 놀이구역좌표
COMMENT ON TABLE ZONE_COORDINATE IS '놀이구역좌표';

-- 놀이구역ID
COMMENT ON COLUMN ZONE_COORDINATE.ZONE_ID IS '놀이구역ID';

-- X좌표
COMMENT ON COLUMN ZONE_COORDINATE.X_COORDINATE IS 'X좌표';

-- Y좌표
COMMENT ON COLUMN ZONE_COORDINATE.Y_COORDINATE IS 'Y좌표';

-- 놀이구역쾌적도일통계
CREATE TABLE ZONE_AIR_DAY_STATISTICS
(
	ZONE_ID            varchar(50) NOT NULL, -- 놀이구역ID
	DATE               date        NOT NULL, -- 일시
	AVERAGE_CO2        integer     NULL,     -- 평균이산화탄소
	AVERAGE_TEMPRATURE integer     NULL,     -- 평균온도
	AVERAGE_HUMIDITY   integer     NULL,     -- 평균습도
	AVERAGE_DUST       integer     NULL      -- 평균먼지
);

-- 놀이구역쾌적도일통계
COMMENT ON TABLE ZONE_AIR_DAY_STATISTICS IS '놀이구역쾌적도일통계';

-- 놀이구역ID
COMMENT ON COLUMN ZONE_AIR_DAY_STATISTICS.ZONE_ID IS '놀이구역ID';

-- 일시
COMMENT ON COLUMN ZONE_AIR_DAY_STATISTICS.DATE IS '일시';

-- 평균이산화탄소
COMMENT ON COLUMN ZONE_AIR_DAY_STATISTICS.AVERAGE_CO2 IS '평균이산화탄소';

-- 평균온도
COMMENT ON COLUMN ZONE_AIR_DAY_STATISTICS.AVERAGE_TEMPRATURE IS '평균온도';

-- 평균습도
COMMENT ON COLUMN ZONE_AIR_DAY_STATISTICS.AVERAGE_HUMIDITY IS '평균습도';

-- 평균먼지
COMMENT ON COLUMN ZONE_AIR_DAY_STATISTICS.AVERAGE_DUST IS '평균먼지';

-- 놀이구역쾌적도일통계 기본키
CREATE UNIQUE INDEX PK_ZONE_AIR_DAY_STATISTICS
	ON ZONE_AIR_DAY_STATISTICS
	( -- 놀이구역쾌적도일통계
		ZONE_ID ASC, -- 놀이구역ID
		DATE ASC -- 일시
	)
;
-- 놀이구역쾌적도일통계
ALTER TABLE ZONE_AIR_DAY_STATISTICS
	ADD CONSTRAINT PK_ZONE_AIR_DAY_STATISTICS
		 -- 놀이구역쾌적도일통계 기본키
	PRIMARY KEY 
	USING INDEX PK_ZONE_AIR_DAY_STATISTICS;

-- 놀이구역쾌적도일통계 기본키
COMMENT ON CONSTRAINT PK_ZONE_AIR_DAY_STATISTICS ON ZONE_AIR_DAY_STATISTICS IS '놀이구역쾌적도일통계 기본키';

-- 놀이구역디바이스
CREATE TABLE ZONE_DEVICE
(
	ID      varchar(50) NOT NULL, -- ID
	ZONE_ID varchar(50) NULL      -- 놀이구역ID
);

-- 놀이구역디바이스
COMMENT ON TABLE ZONE_DEVICE IS '놀이구역디바이스';

-- ID
COMMENT ON COLUMN ZONE_DEVICE.ID IS 'ID';

-- 놀이구역ID
COMMENT ON COLUMN ZONE_DEVICE.ZONE_ID IS '놀이구역ID';

-- 놀이구역디바이스 기본키
CREATE UNIQUE INDEX PK_ZONE_DEVICE
	ON ZONE_DEVICE
	( -- 놀이구역디바이스
		ID ASC -- ID
	)
;
-- 놀이구역디바이스
ALTER TABLE ZONE_DEVICE
	ADD CONSTRAINT PK_ZONE_DEVICE
		 -- 놀이구역디바이스 기본키
	PRIMARY KEY 
	USING INDEX PK_ZONE_DEVICE;

-- 놀이구역디바이스 기본키
COMMENT ON CONSTRAINT PK_ZONE_DEVICE ON ZONE_DEVICE IS '놀이구역디바이스 기본키';

-- 음식
CREATE TABLE FOOD
(
	ID      varchar(50) NOT NULL, -- ID
	CALORIE integer     NULL,     -- 칼로리
	NAME    varchar(50) NULL      -- 음식명
);

-- 음식
COMMENT ON TABLE FOOD IS '음식';

-- ID
COMMENT ON COLUMN FOOD.ID IS 'ID';

-- 칼로리
COMMENT ON COLUMN FOOD.CALORIE IS '칼로리';

-- 음식명
COMMENT ON COLUMN FOOD.NAME IS '음식명';

-- 음식 기본키
CREATE UNIQUE INDEX PK_FOOD
	ON FOOD
	( -- 음식
		ID ASC -- ID
	)
;
-- 음식
ALTER TABLE FOOD
	ADD CONSTRAINT PK_FOOD
		 -- 음식 기본키
	PRIMARY KEY 
	USING INDEX PK_FOOD;

-- 음식 기본키
COMMENT ON CONSTRAINT PK_FOOD ON FOOD IS '음식 기본키';

-- 놀이구역
CREATE TABLE ZONE
(
	ID                  varchar(50) NOT NULL, -- ID
	NAME                varchar(50) NULL,     -- 이름
	MAX_CAPACITY        integer     NULL,     -- 수용인원
	CURRENT_USING_COUNT integer     NULL,     -- 현재이용인원
	LIMIT_AGE           integer     NULL,     -- 제한연령
	STATE_CODE          varchar(10) NULL      -- 상태코드
);

-- 놀이구역
COMMENT ON TABLE ZONE IS '놀이구역';

-- ID
COMMENT ON COLUMN ZONE.ID IS 'ID';

-- 이름
COMMENT ON COLUMN ZONE.NAME IS '이름';

-- 수용인원
COMMENT ON COLUMN ZONE.MAX_CAPACITY IS '수용인원';

-- 현재이용인원
COMMENT ON COLUMN ZONE.CURRENT_USING_COUNT IS '현재이용인원';

-- 제한연령
COMMENT ON COLUMN ZONE.LIMIT_AGE IS '제한연령';

-- 상태코드
COMMENT ON COLUMN ZONE.STATE_CODE IS '상태코드';

-- 놀이구역 기본키
CREATE UNIQUE INDEX PK_ZONE
	ON ZONE
	( -- 놀이구역
		ID ASC -- ID
	)
;
-- 놀이구역
ALTER TABLE ZONE
	ADD CONSTRAINT PK_ZONE
		 -- 놀이구역 기본키
	PRIMARY KEY 
	USING INDEX PK_ZONE;

-- 놀이구역 기본키
COMMENT ON CONSTRAINT PK_ZONE ON ZONE IS '놀이구역 기본키';

-- 연령별활동일통계
CREATE TABLE AGE_ACTIVITY_DAY_STATISTICS
(
	DATE    date    NOT NULL, -- 일시
	AGE     integer NOT NULL, -- 연령
	AVERAGE integer NULL,     -- 평균활동량
	MAXIMUM integer NULL,     -- 최대활동량
	MINIMUM integer NULL      -- 최소활동량
);

-- 연령별활동일통계
COMMENT ON TABLE AGE_ACTIVITY_DAY_STATISTICS IS '연령별활동일통계';

-- 일시
COMMENT ON COLUMN AGE_ACTIVITY_DAY_STATISTICS.DATE IS '일시';

-- 연령
COMMENT ON COLUMN AGE_ACTIVITY_DAY_STATISTICS.AGE IS '연령';

-- 평균활동량
COMMENT ON COLUMN AGE_ACTIVITY_DAY_STATISTICS.AVERAGE IS '평균활동량';

-- 최대활동량
COMMENT ON COLUMN AGE_ACTIVITY_DAY_STATISTICS.MAXIMUM IS '최대활동량';

-- 최소활동량
COMMENT ON COLUMN AGE_ACTIVITY_DAY_STATISTICS.MINIMUM IS '최소활동량';

-- 연령별활동일통계 기본키
CREATE UNIQUE INDEX PK_AGE_ACTIVITY_DAY_STATISTICS
	ON AGE_ACTIVITY_DAY_STATISTICS
	( -- 연령별활동일통계
		DATE ASC, -- 일시
		AGE ASC -- 연령
	)
;
-- 연령별활동일통계
ALTER TABLE AGE_ACTIVITY_DAY_STATISTICS
	ADD CONSTRAINT PK_AGE_ACTIVITY_DAY_STATISTICS
		 -- 연령별활동일통계 기본키
	PRIMARY KEY 
	USING INDEX PK_AGE_ACTIVITY_DAY_STATISTICS;

-- 연령별활동일통계 기본키
COMMENT ON CONSTRAINT PK_AGE_ACTIVITY_DAY_STATISTICS ON AGE_ACTIVITY_DAY_STATISTICS IS '연령별활동일통계 기본키';

-- 방문이력별이용통계
CREATE TABLE ZONE_USING_ONE_DAY_STATISTICS
(
	CHILD_ID       varchar(50) NOT NULL, -- 자녀ID
	START_TIME     date        NOT NULL, -- 입장시간
	ZONE_ID        varchar(50) NULL,     -- 놀이구역ID
	VISITING_COUNT integer     NULL      -- 방문횟수
);

-- 방문이력별이용통계
COMMENT ON TABLE ZONE_USING_ONE_DAY_STATISTICS IS '방문이력별이용통계';

-- 자녀ID
COMMENT ON COLUMN ZONE_USING_ONE_DAY_STATISTICS.CHILD_ID IS '자녀ID';

-- 입장시간
COMMENT ON COLUMN ZONE_USING_ONE_DAY_STATISTICS.START_TIME IS '입장시간';

-- 놀이구역ID
COMMENT ON COLUMN ZONE_USING_ONE_DAY_STATISTICS.ZONE_ID IS '놀이구역ID';

-- 방문횟수
COMMENT ON COLUMN ZONE_USING_ONE_DAY_STATISTICS.VISITING_COUNT IS '방문횟수';

-- 방문이력별이용통계 기본키
CREATE UNIQUE INDEX PK_ZONE_USING_ONE_DAY_STATISTICS
	ON ZONE_USING_ONE_DAY_STATISTICS
	( -- 방문이력별이용통계
		CHILD_ID ASC, -- 자녀ID
		START_TIME ASC -- 입장시간
	)
;
-- 방문이력별이용통계
ALTER TABLE ZONE_USING_ONE_DAY_STATISTICS
	ADD CONSTRAINT PK_ZONE_USING_ONE_DAY_STATISTICS
		 -- 방문이력별이용통계 기본키
	PRIMARY KEY 
	USING INDEX PK_ZONE_USING_ONE_DAY_STATISTICS;

-- 방문이력별이용통계 기본키
COMMENT ON CONSTRAINT PK_ZONE_USING_ONE_DAY_STATISTICS ON ZONE_USING_ONE_DAY_STATISTICS IS '방문이력별이용통계 기본키';

-- 자녀활동량일통계
CREATE TABLE CHILD_ACTIVITY_WEEKLY_STATISTICS
(
	CHILD_ID varchar(50) NOT NULL, -- 자녀ID
	DATE     date        NOT NULL, -- 일시
	AVERAGE  integer     NULL,     -- 평균활동량
	MAXIMUM  integer     NULL,     -- 최대활동량
	MINIMUM  integer     NULL      -- 최소활동량
);

-- 자녀활동량일통계
COMMENT ON TABLE CHILD_ACTIVITY_WEEKLY_STATISTICS IS '자녀활동량일통계';

-- 자녀ID
COMMENT ON COLUMN CHILD_ACTIVITY_WEEKLY_STATISTICS.CHILD_ID IS '자녀ID';

-- 일시
COMMENT ON COLUMN CHILD_ACTIVITY_WEEKLY_STATISTICS.DATE IS '일시';

-- 평균활동량
COMMENT ON COLUMN CHILD_ACTIVITY_WEEKLY_STATISTICS.AVERAGE IS '평균활동량';

-- 최대활동량
COMMENT ON COLUMN CHILD_ACTIVITY_WEEKLY_STATISTICS.MAXIMUM IS '최대활동량';

-- 최소활동량
COMMENT ON COLUMN CHILD_ACTIVITY_WEEKLY_STATISTICS.MINIMUM IS '최소활동량';

-- 자녀활동량일통계 기본키
CREATE UNIQUE INDEX PK_CHILD_ACTIVITY_WEEKLY_STATISTICS
	ON CHILD_ACTIVITY_WEEKLY_STATISTICS
	( -- 자녀활동량일통계
		CHILD_ID ASC, -- 자녀ID
		DATE ASC -- 일시
	)
;
-- 자녀활동량일통계
ALTER TABLE CHILD_ACTIVITY_WEEKLY_STATISTICS
	ADD CONSTRAINT PK_CHILD_ACTIVITY_WEEKLY_STATISTICS
		 -- 자녀활동량일통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CHILD_ACTIVITY_WEEKLY_STATISTICS;

-- 자녀활동량일통계 기본키
COMMENT ON CONSTRAINT PK_CHILD_ACTIVITY_WEEKLY_STATISTICS ON CHILD_ACTIVITY_WEEKLY_STATISTICS IS '자녀활동량일통계 기본키';

-- 키즈카페매출시통계
CREATE TABLE CAFE_INCOME_HOUR_STATISTICS
(
	DATE    date    NOT NULL, -- 일시
	AVERAGE integer NULL,     -- 평균매출
	MAXIMUM integer NULL,     -- 최대매출
	MINIMUM integer NULL      -- 최소매출
);

-- 키즈카페매출시통계
COMMENT ON TABLE CAFE_INCOME_HOUR_STATISTICS IS '키즈카페매출시통계';

-- 일시
COMMENT ON COLUMN CAFE_INCOME_HOUR_STATISTICS.DATE IS '일시';

-- 평균매출
COMMENT ON COLUMN CAFE_INCOME_HOUR_STATISTICS.AVERAGE IS '평균매출';

-- 최대매출
COMMENT ON COLUMN CAFE_INCOME_HOUR_STATISTICS.MAXIMUM IS '최대매출';

-- 최소매출
COMMENT ON COLUMN CAFE_INCOME_HOUR_STATISTICS.MINIMUM IS '최소매출';

-- 키즈카페매출시통계 기본키
CREATE UNIQUE INDEX PK_CAFE_INCOME_HOUR_STATISTICS
	ON CAFE_INCOME_HOUR_STATISTICS
	( -- 키즈카페매출시통계
		DATE ASC -- 일시
	)
;
-- 키즈카페매출시통계
ALTER TABLE CAFE_INCOME_HOUR_STATISTICS
	ADD CONSTRAINT PK_CAFE_INCOME_HOUR_STATISTICS
		 -- 키즈카페매출시통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CAFE_INCOME_HOUR_STATISTICS;

-- 키즈카페매출시통계 기본키
COMMENT ON CONSTRAINT PK_CAFE_INCOME_HOUR_STATISTICS ON CAFE_INCOME_HOUR_STATISTICS IS '키즈카페매출시통계 기본키';

-- 연령별활동량시통계
CREATE TABLE AGE_ACTIVITY_HOUR_STATISTICS
(
	DATE    date    NOT NULL, -- 일시
	AGE     integer NOT NULL, -- 연령
	AVERAGE integer NULL,     -- 평균활동량
	MAXIMUM integer NULL,     -- 최대활동량
	MINIMUM integer NULL      -- 최소활동량
);

-- 연령별활동량시통계
COMMENT ON TABLE AGE_ACTIVITY_HOUR_STATISTICS IS '연령별활동량시통계';

-- 일시
COMMENT ON COLUMN AGE_ACTIVITY_HOUR_STATISTICS.DATE IS '일시';

-- 연령
COMMENT ON COLUMN AGE_ACTIVITY_HOUR_STATISTICS.AGE IS '연령';

-- 평균활동량
COMMENT ON COLUMN AGE_ACTIVITY_HOUR_STATISTICS.AVERAGE IS '평균활동량';

-- 최대활동량
COMMENT ON COLUMN AGE_ACTIVITY_HOUR_STATISTICS.MAXIMUM IS '최대활동량';

-- 최소활동량
COMMENT ON COLUMN AGE_ACTIVITY_HOUR_STATISTICS.MINIMUM IS '최소활동량';

-- 연령별활동량시통계 기본키
CREATE UNIQUE INDEX PK_AGE_ACTIVITY_HOUR_STATISTICS
	ON AGE_ACTIVITY_HOUR_STATISTICS
	( -- 연령별활동량시통계
		DATE ASC, -- 일시
		AGE ASC -- 연령
	)
;
-- 연령별활동량시통계
ALTER TABLE AGE_ACTIVITY_HOUR_STATISTICS
	ADD CONSTRAINT PK_AGE_ACTIVITY_HOUR_STATISTICS
		 -- 연령별활동량시통계 기본키
	PRIMARY KEY 
	USING INDEX PK_AGE_ACTIVITY_HOUR_STATISTICS;

-- 연령별활동량시통계 기본키
COMMENT ON CONSTRAINT PK_AGE_ACTIVITY_HOUR_STATISTICS ON AGE_ACTIVITY_HOUR_STATISTICS IS '연령별활동량시통계 기본키';

-- 키즈카페이용일통계
CREATE TABLE CAFE_USAGE_DAY_STATISTICS
(
	DATE    date    NOT NULL, -- 일시
	AGE     integer NOT NULL, -- 연령
	AVERAGE integer NULL,     -- 평균고객수
	MAXIMUM integer NULL,     -- 최대고객수
	MINIMUM integer NULL      -- 최소고객수
);

-- 키즈카페이용일통계
COMMENT ON TABLE CAFE_USAGE_DAY_STATISTICS IS '키즈카페이용일통계';

-- 일시
COMMENT ON COLUMN CAFE_USAGE_DAY_STATISTICS.DATE IS '일시';

-- 연령
COMMENT ON COLUMN CAFE_USAGE_DAY_STATISTICS.AGE IS '연령';

-- 평균고객수
COMMENT ON COLUMN CAFE_USAGE_DAY_STATISTICS.AVERAGE IS '평균고객수';

-- 최대고객수
COMMENT ON COLUMN CAFE_USAGE_DAY_STATISTICS.MAXIMUM IS '최대고객수';

-- 최소고객수
COMMENT ON COLUMN CAFE_USAGE_DAY_STATISTICS.MINIMUM IS '최소고객수';

-- 키즈카페이용일통계 기본키
CREATE UNIQUE INDEX PK_CAFE_USAGE_DAY_STATISTICS
	ON CAFE_USAGE_DAY_STATISTICS
	( -- 키즈카페이용일통계
		DATE ASC, -- 일시
		AGE ASC -- 연령
	)
;
-- 키즈카페이용일통계
ALTER TABLE CAFE_USAGE_DAY_STATISTICS
	ADD CONSTRAINT PK_CAFE_USAGE_DAY_STATISTICS
		 -- 키즈카페이용일통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CAFE_USAGE_DAY_STATISTICS;

-- 키즈카페이용일통계 기본키
COMMENT ON CONSTRAINT PK_CAFE_USAGE_DAY_STATISTICS ON CAFE_USAGE_DAY_STATISTICS IS '키즈카페이용일통계 기본키';

-- 자녀놀이구역방문일통계
CREATE TABLE CHILD_ZONE_VISITING_DAY_STATISTICS
(
	ID      varchar(50) NOT NULL, -- ID
	ZONE_ID varchar(50) NOT NULL, -- 놀이구역ID
	DATE    date        NOT NULL, -- 일시
	AVERAGE integer     NULL      -- 평균방문횟수
);

-- 자녀놀이구역방문일통계
COMMENT ON TABLE CHILD_ZONE_VISITING_DAY_STATISTICS IS '자녀놀이구역방문일통계';

-- ID
COMMENT ON COLUMN CHILD_ZONE_VISITING_DAY_STATISTICS.ID IS 'ID';

-- 놀이구역ID
COMMENT ON COLUMN CHILD_ZONE_VISITING_DAY_STATISTICS.ZONE_ID IS '놀이구역ID';

-- 일시
COMMENT ON COLUMN CHILD_ZONE_VISITING_DAY_STATISTICS.DATE IS '일시';

-- 평균방문횟수
COMMENT ON COLUMN CHILD_ZONE_VISITING_DAY_STATISTICS.AVERAGE IS '평균방문횟수';

-- 자녀놀이구역방문일통계 기본키
CREATE UNIQUE INDEX PK_CHILD_ZONE_VISITING_DAY_STATISTICS
	ON CHILD_ZONE_VISITING_DAY_STATISTICS
	( -- 자녀놀이구역방문일통계
		ID ASC, -- ID
		ZONE_ID ASC, -- 놀이구역ID
		DATE ASC -- 일시
	)
;
-- 자녀놀이구역방문일통계
ALTER TABLE CHILD_ZONE_VISITING_DAY_STATISTICS
	ADD CONSTRAINT PK_CHILD_ZONE_VISITING_DAY_STATISTICS
		 -- 자녀놀이구역방문일통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CHILD_ZONE_VISITING_DAY_STATISTICS;

-- 자녀놀이구역방문일통계 기본키
COMMENT ON CONSTRAINT PK_CHILD_ZONE_VISITING_DAY_STATISTICS ON CHILD_ZONE_VISITING_DAY_STATISTICS IS '자녀놀이구역방문일통계 기본키';

-- 자녀심박수시통계
CREATE TABLE CHILD_PULSE_HOUR_STATISTICS
(
	CHILD_ID varchar(50) NOT NULL, -- 자녀ID
	DATE     date        NOT NULL, -- 일시
	AVERAGE  integer     NULL,     -- 평균심박수
	MAXIMUM  integer     NULL,     -- 최대심박수
	MINIMUM  integer     NULL      -- 최소심박수
);

-- 자녀심박수시통계
COMMENT ON TABLE CHILD_PULSE_HOUR_STATISTICS IS '자녀심박수시통계';

-- 자녀ID
COMMENT ON COLUMN CHILD_PULSE_HOUR_STATISTICS.CHILD_ID IS '자녀ID';

-- 일시
COMMENT ON COLUMN CHILD_PULSE_HOUR_STATISTICS.DATE IS '일시';

-- 평균심박수
COMMENT ON COLUMN CHILD_PULSE_HOUR_STATISTICS.AVERAGE IS '평균심박수';

-- 최대심박수
COMMENT ON COLUMN CHILD_PULSE_HOUR_STATISTICS.MAXIMUM IS '최대심박수';

-- 최소심박수
COMMENT ON COLUMN CHILD_PULSE_HOUR_STATISTICS.MINIMUM IS '최소심박수';

-- 자녀심박수시통계 기본키
CREATE UNIQUE INDEX PK_CHILD_PULSE_HOUR_STATISTICS
	ON CHILD_PULSE_HOUR_STATISTICS
	( -- 자녀심박수시통계
		CHILD_ID ASC, -- 자녀ID
		DATE ASC -- 일시
	)
;
-- 자녀심박수시통계
ALTER TABLE CHILD_PULSE_HOUR_STATISTICS
	ADD CONSTRAINT PK_CHILD_PULSE_HOUR_STATISTICS
		 -- 자녀심박수시통계 기본키
	PRIMARY KEY 
	USING INDEX PK_CHILD_PULSE_HOUR_STATISTICS;

-- 자녀심박수시통계 기본키
COMMENT ON CONSTRAINT PK_CHILD_PULSE_HOUR_STATISTICS ON CHILD_PULSE_HOUR_STATISTICS IS '자녀심박수시통계 기본키';

-- 놀이구역방문시통계
CREATE TABLE ZONE_VISITING_HOUR_STATISTICS
(
	ZONE_ID varchar(50) NOT NULL, -- 놀이구역ID
	AGE     integer     NOT NULL, -- 나이
	DATE    date        NOT NULL, -- 일시
	AVERAGE integer     NOT NULL, -- 평균방문횟수
	MINIMUM integer     NULL,     -- 최소방문횟수
	MAXIMUM integer     NULL      -- 최대방문횟수
);

-- 놀이구역방문시통계
COMMENT ON TABLE ZONE_VISITING_HOUR_STATISTICS IS '놀이구역방문시통계';

-- 놀이구역ID
COMMENT ON COLUMN ZONE_VISITING_HOUR_STATISTICS.ZONE_ID IS '놀이구역ID';

-- 나이
COMMENT ON COLUMN ZONE_VISITING_HOUR_STATISTICS.AGE IS '나이';

-- 일시
COMMENT ON COLUMN ZONE_VISITING_HOUR_STATISTICS.DATE IS '일시';

-- 평균방문횟수
COMMENT ON COLUMN ZONE_VISITING_HOUR_STATISTICS.AVERAGE IS '평균방문횟수';

-- 최소방문횟수
COMMENT ON COLUMN ZONE_VISITING_HOUR_STATISTICS.MINIMUM IS '최소방문횟수';

-- 최대방문횟수
COMMENT ON COLUMN ZONE_VISITING_HOUR_STATISTICS.MAXIMUM IS '최대방문횟수';

-- 놀이구역방문시통계 기본키
CREATE UNIQUE INDEX PK_ZONE_VISITING_HOUR_STATISTICS
	ON ZONE_VISITING_HOUR_STATISTICS
	( -- 놀이구역방문시통계
		ZONE_ID ASC, -- 놀이구역ID
		AGE ASC, -- 나이
		DATE ASC -- 일시
	)
;
-- 놀이구역방문시통계
ALTER TABLE ZONE_VISITING_HOUR_STATISTICS
	ADD CONSTRAINT PK_ZONE_VISITING_HOUR_STATISTICS
		 -- 놀이구역방문시통계 기본키
	PRIMARY KEY 
	USING INDEX PK_ZONE_VISITING_HOUR_STATISTICS;

-- 놀이구역방문시통계 기본키
COMMENT ON CONSTRAINT PK_ZONE_VISITING_HOUR_STATISTICS ON ZONE_VISITING_HOUR_STATISTICS IS '놀이구역방문시통계 기본키';

-- 놀이구역쾌적도시통계
CREATE TABLE ZONE_AIR_HOUR_STATISTICS
(
	ZONE_ID            varchar(50) NOT NULL, -- 놀이구역ID
	DATE               date        NOT NULL, -- 일시
	AVERAGE_CO2        integer     NULL,     -- 평균이산화탄소
	AVERAGE_TEMPARTURE integer     NULL,     -- 평균온도
	AVERAGE_HUMIDITY   integer     NULL,     -- 평균습도
	AVERAGE_DUST       integer     NULL      -- 평균먼지
);

-- 놀이구역쾌적도시통계
COMMENT ON TABLE ZONE_AIR_HOUR_STATISTICS IS '놀이구역쾌적도시통계';

-- 놀이구역ID
COMMENT ON COLUMN ZONE_AIR_HOUR_STATISTICS.ZONE_ID IS '놀이구역ID';

-- 일시
COMMENT ON COLUMN ZONE_AIR_HOUR_STATISTICS.DATE IS '일시';

-- 평균이산화탄소
COMMENT ON COLUMN ZONE_AIR_HOUR_STATISTICS.AVERAGE_CO2 IS '평균이산화탄소';

-- 평균온도
COMMENT ON COLUMN ZONE_AIR_HOUR_STATISTICS.AVERAGE_TEMPARTURE IS '평균온도';

-- 평균습도
COMMENT ON COLUMN ZONE_AIR_HOUR_STATISTICS.AVERAGE_HUMIDITY IS '평균습도';

-- 평균먼지
COMMENT ON COLUMN ZONE_AIR_HOUR_STATISTICS.AVERAGE_DUST IS '평균먼지';

-- 놀이구역쾌적도시통계 기본키
CREATE UNIQUE INDEX PK_ZONE_AIR_HOUR_STATISTICS
	ON ZONE_AIR_HOUR_STATISTICS
	( -- 놀이구역쾌적도시통계
		ZONE_ID ASC, -- 놀이구역ID
		DATE ASC -- 일시
	)
;
-- 놀이구역쾌적도시통계
ALTER TABLE ZONE_AIR_HOUR_STATISTICS
	ADD CONSTRAINT PK_ZONE_AIR_HOUR_STATISTICS
		 -- 놀이구역쾌적도시통계 기본키
	PRIMARY KEY 
	USING INDEX PK_ZONE_AIR_HOUR_STATISTICS;

-- 놀이구역쾌적도시통계 기본키
COMMENT ON CONSTRAINT PK_ZONE_AIR_HOUR_STATISTICS ON ZONE_AIR_HOUR_STATISTICS IS '놀이구역쾌적도시통계 기본키';

-- 키즈카페방문이력
ALTER TABLE CAFE_VISITING_RECORD
	ADD CONSTRAINT FK_K_CHILD_TO_CAFE_VISITING_RECORD
	 -- 자녀 -> 키즈카페방문이력
		FOREIGN KEY (
			CHILD_ID -- 자녀ID
		)
		REFERENCES K_CHILD ( -- 자녀
			ID -- ID
		);

-- 자녀 -> 키즈카페방문이력
COMMENT ON CONSTRAINT FK_K_CHILD_TO_CAFE_VISITING_RECORD ON CAFE_VISITING_RECORD IS '자녀 -> 키즈카페방문이력';

-- 키즈카페방문이력
ALTER TABLE CAFE_VISITING_RECORD
	ADD CONSTRAINT FK_BAND_DEVICE_TO_CAFE_VISITING_RECORD
	 -- 밴드디바이스 -> 키즈카페방문이력
		FOREIGN KEY (
			BAND_DEVICE_ID -- 밴드디바이스ID
		)
		REFERENCES BAND_DEVICE ( -- 밴드디바이스
			ID -- ID
		);

-- 밴드디바이스 -> 키즈카페방문이력
COMMENT ON CONSTRAINT FK_BAND_DEVICE_TO_CAFE_VISITING_RECORD ON CAFE_VISITING_RECORD IS '밴드디바이스 -> 키즈카페방문이력';

-- 자녀
ALTER TABLE K_CHILD
	ADD CONSTRAINT FK_K_USER_TO_K_CHILD
	 -- 회원 -> 자녀
		FOREIGN KEY (
			USER_ID -- 회원ID
		)
		REFERENCES K_USER ( -- 회원
			ID -- ID
		);

-- 회원 -> 자녀
COMMENT ON CONSTRAINT FK_K_USER_TO_K_CHILD ON K_CHILD IS '회원 -> 자녀';

-- 자녀놀이구역방문시통계
ALTER TABLE CHILD_ZONE_VISITING_HOUR_STATISTICS
	ADD CONSTRAINT FK_K_CHILD_TO_CHILD_ZONE_VISITING_HOUR_STATISTICS
	 -- 자녀 -> 자녀놀이구역방문시통계
		FOREIGN KEY (
			CHILD_ID -- 자녀ID
		)
		REFERENCES K_CHILD ( -- 자녀
			ID -- ID
		);

-- 자녀 -> 자녀놀이구역방문시통계
COMMENT ON CONSTRAINT FK_K_CHILD_TO_CHILD_ZONE_VISITING_HOUR_STATISTICS ON CHILD_ZONE_VISITING_HOUR_STATISTICS IS '자녀 -> 자녀놀이구역방문시통계';

-- 자녀놀이구역방문시통계
ALTER TABLE CHILD_ZONE_VISITING_HOUR_STATISTICS
	ADD CONSTRAINT FK_ZONE_TO_CHILD_ZONE_VISITING_HOUR_STATISTICS
	 -- 놀이구역 -> 자녀놀이구역방문시통계
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 자녀놀이구역방문시통계
COMMENT ON CONSTRAINT FK_ZONE_TO_CHILD_ZONE_VISITING_HOUR_STATISTICS ON CHILD_ZONE_VISITING_HOUR_STATISTICS IS '놀이구역 -> 자녀놀이구역방문시통계';

-- 자녀활동량시통계
ALTER TABLE CHILD_ACTIVITY_DAILY_STATISTICS
	ADD CONSTRAINT FK_K_CHILD_TO_CHILD_ACTIVITY_DAILY_STATISTICS
	 -- 자녀 -> 자녀활동량시통계
		FOREIGN KEY (
			CHILD_ID -- 자녀ID
		)
		REFERENCES K_CHILD ( -- 자녀
			ID -- ID
		);

-- 자녀 -> 자녀활동량시통계
COMMENT ON CONSTRAINT FK_K_CHILD_TO_CHILD_ACTIVITY_DAILY_STATISTICS ON CHILD_ACTIVITY_DAILY_STATISTICS IS '자녀 -> 자녀활동량시통계';

-- 밴드디바이스
ALTER TABLE BAND_DEVICE
	ADD CONSTRAINT FK_ZONE_TO_BAND_DEVICE2
	 -- 놀이구역 -> 밴드디바이스2
		FOREIGN KEY (
			CURRENT_LOCATION -- 현재위치
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 밴드디바이스2
COMMENT ON CONSTRAINT FK_ZONE_TO_BAND_DEVICE2 ON BAND_DEVICE IS '놀이구역 -> 밴드디바이스2';

-- 밴드디바이스
ALTER TABLE BAND_DEVICE
	ADD CONSTRAINT FK_ZONE_TO_BAND_DEVICE
	 -- 놀이구역 -> 밴드디바이스
		FOREIGN KEY (
			BEFORE_LOCATION -- 이전위치
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 밴드디바이스
COMMENT ON CONSTRAINT FK_ZONE_TO_BAND_DEVICE ON BAND_DEVICE IS '놀이구역 -> 밴드디바이스';

-- 자녀섭취가능음식
ALTER TABLE CHILD_EATABLE
	ADD CONSTRAINT FK_K_CHILD_TO_CHILD_EATABLE
	 -- 자녀 -> 자녀섭취가능음식
		FOREIGN KEY (
			CHILD_ID -- 자녀ID
		)
		REFERENCES K_CHILD ( -- 자녀
			ID -- ID
		);

-- 자녀 -> 자녀섭취가능음식
COMMENT ON CONSTRAINT FK_K_CHILD_TO_CHILD_EATABLE ON CHILD_EATABLE IS '자녀 -> 자녀섭취가능음식';

-- 자녀섭취가능음식
ALTER TABLE CHILD_EATABLE
	ADD CONSTRAINT FK_FOOD_TO_CHILD_EATABLE
	 -- 음식 -> 자녀섭취가능음식
		FOREIGN KEY (
			FOOD_ID -- 음식ID
		)
		REFERENCES FOOD ( -- 음식
			ID -- ID
		);

-- 음식 -> 자녀섭취가능음식
COMMENT ON CONSTRAINT FK_FOOD_TO_CHILD_EATABLE ON CHILD_EATABLE IS '음식 -> 자녀섭취가능음식';

-- 놀이구역방문일통계
ALTER TABLE ZONE_VISITING_DAY_STATISTICS
	ADD CONSTRAINT FK_ZONE_TO_ZONE_VISITING_DAY_STATISTICS
	 -- 놀이구역 -> 놀이구역방문일통계
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 놀이구역방문일통계
COMMENT ON CONSTRAINT FK_ZONE_TO_ZONE_VISITING_DAY_STATISTICS ON ZONE_VISITING_DAY_STATISTICS IS '놀이구역 -> 놀이구역방문일통계';

-- 자녀심박수10분통계
ALTER TABLE CHILD_PULSE_10M_STATISTICS
	ADD CONSTRAINT FK_K_CHILD_TO_CHILD_PULSE_10M_STATISTICS
	 -- 자녀 -> 자녀심박수10분통계
		FOREIGN KEY (
			CHILD_ID -- 자녀ID
		)
		REFERENCES K_CHILD ( -- 자녀
			ID -- ID
		);

-- 자녀 -> 자녀심박수10분통계
COMMENT ON CONSTRAINT FK_K_CHILD_TO_CHILD_PULSE_10M_STATISTICS ON CHILD_PULSE_10M_STATISTICS IS '자녀 -> 자녀심박수10분통계';

-- 놀이구역좌표
ALTER TABLE ZONE_COORDINATE
	ADD CONSTRAINT FK_ZONE_TO_ZONE_COORDINATE
	 -- 놀이구역 -> 놀이구역좌표
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 놀이구역좌표
COMMENT ON CONSTRAINT FK_ZONE_TO_ZONE_COORDINATE ON ZONE_COORDINATE IS '놀이구역 -> 놀이구역좌표';

-- 놀이구역쾌적도일통계
ALTER TABLE ZONE_AIR_DAY_STATISTICS
	ADD CONSTRAINT FK_ZONE_TO_ZONE_AIR_DAY_STATISTICS
	 -- 놀이구역 -> 놀이구역쾌적도일통계
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 놀이구역쾌적도일통계
COMMENT ON CONSTRAINT FK_ZONE_TO_ZONE_AIR_DAY_STATISTICS ON ZONE_AIR_DAY_STATISTICS IS '놀이구역 -> 놀이구역쾌적도일통계';

-- 놀이구역디바이스
ALTER TABLE ZONE_DEVICE
	ADD CONSTRAINT FK_ZONE_TO_ZONE_DEVICE
	 -- 놀이구역 -> 놀이구역디바이스
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 놀이구역디바이스
COMMENT ON CONSTRAINT FK_ZONE_TO_ZONE_DEVICE ON ZONE_DEVICE IS '놀이구역 -> 놀이구역디바이스';

-- 방문이력별이용통계
ALTER TABLE ZONE_USING_ONE_DAY_STATISTICS
	ADD CONSTRAINT FK_CAFE_VISITING_RECORD_TO_ZONE_USING_ONE_DAY_STATISTICS
	 -- 키즈카페방문이력 -> 방문이력별이용통계
		FOREIGN KEY (
			CHILD_ID,   -- 자녀ID
			START_TIME  -- 입장시간
		)
		REFERENCES CAFE_VISITING_RECORD ( -- 키즈카페방문이력
			CHILD_ID,   -- 자녀ID
			START_TIME  -- 입장시간
		);

-- 키즈카페방문이력 -> 방문이력별이용통계
COMMENT ON CONSTRAINT FK_CAFE_VISITING_RECORD_TO_ZONE_USING_ONE_DAY_STATISTICS ON ZONE_USING_ONE_DAY_STATISTICS IS '키즈카페방문이력 -> 방문이력별이용통계';

-- 방문이력별이용통계
ALTER TABLE ZONE_USING_ONE_DAY_STATISTICS
	ADD CONSTRAINT FK_ZONE_TO_ZONE_USING_ONE_DAY_STATISTICS
	 -- 놀이구역 -> 방문이력별이용통계
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 방문이력별이용통계
COMMENT ON CONSTRAINT FK_ZONE_TO_ZONE_USING_ONE_DAY_STATISTICS ON ZONE_USING_ONE_DAY_STATISTICS IS '놀이구역 -> 방문이력별이용통계';

-- 자녀활동량일통계
ALTER TABLE CHILD_ACTIVITY_WEEKLY_STATISTICS
	ADD CONSTRAINT FK_K_CHILD_TO_CHILD_ACTIVITY_WEEKLY_STATISTICS
	 -- 자녀 -> 자녀활동량일통계
		FOREIGN KEY (
			CHILD_ID -- 자녀ID
		)
		REFERENCES K_CHILD ( -- 자녀
			ID -- ID
		);

-- 자녀 -> 자녀활동량일통계
COMMENT ON CONSTRAINT FK_K_CHILD_TO_CHILD_ACTIVITY_WEEKLY_STATISTICS ON CHILD_ACTIVITY_WEEKLY_STATISTICS IS '자녀 -> 자녀활동량일통계';

-- 자녀놀이구역방문일통계
ALTER TABLE CHILD_ZONE_VISITING_DAY_STATISTICS
	ADD CONSTRAINT FK_K_CHILD_TO_CHILD_ZONE_VISITING_DAY_STATISTICS
	 -- 자녀 -> 자녀놀이구역방문일통계
		FOREIGN KEY (
			ID -- ID
		)
		REFERENCES K_CHILD ( -- 자녀
			ID -- ID
		);

-- 자녀 -> 자녀놀이구역방문일통계
COMMENT ON CONSTRAINT FK_K_CHILD_TO_CHILD_ZONE_VISITING_DAY_STATISTICS ON CHILD_ZONE_VISITING_DAY_STATISTICS IS '자녀 -> 자녀놀이구역방문일통계';

-- 자녀놀이구역방문일통계
ALTER TABLE CHILD_ZONE_VISITING_DAY_STATISTICS
	ADD CONSTRAINT FK_ZONE_TO_CHILD_ZONE_VISITING_DAY_STATISTICS
	 -- 놀이구역 -> 자녀놀이구역방문일통계
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 자녀놀이구역방문일통계
COMMENT ON CONSTRAINT FK_ZONE_TO_CHILD_ZONE_VISITING_DAY_STATISTICS ON CHILD_ZONE_VISITING_DAY_STATISTICS IS '놀이구역 -> 자녀놀이구역방문일통계';

-- 자녀심박수시통계
ALTER TABLE CHILD_PULSE_HOUR_STATISTICS
	ADD CONSTRAINT FK_K_CHILD_TO_CHILD_PULSE_HOUR_STATISTICS
	 -- 자녀 -> 자녀심박수시통계
		FOREIGN KEY (
			CHILD_ID -- 자녀ID
		)
		REFERENCES K_CHILD ( -- 자녀
			ID -- ID
		);

-- 자녀 -> 자녀심박수시통계
COMMENT ON CONSTRAINT FK_K_CHILD_TO_CHILD_PULSE_HOUR_STATISTICS ON CHILD_PULSE_HOUR_STATISTICS IS '자녀 -> 자녀심박수시통계';

-- 놀이구역방문시통계
ALTER TABLE ZONE_VISITING_HOUR_STATISTICS
	ADD CONSTRAINT FK_ZONE_TO_ZONE_VISITING_HOUR_STATISTICS
	 -- 놀이구역 -> 놀이구역방문시통계
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 놀이구역방문시통계
COMMENT ON CONSTRAINT FK_ZONE_TO_ZONE_VISITING_HOUR_STATISTICS ON ZONE_VISITING_HOUR_STATISTICS IS '놀이구역 -> 놀이구역방문시통계';

-- 놀이구역쾌적도시통계
ALTER TABLE ZONE_AIR_HOUR_STATISTICS
	ADD CONSTRAINT FK_ZONE_TO_ZONE_AIR_HOUR_STATISTICS
	 -- 놀이구역 -> 놀이구역쾌적도시통계
		FOREIGN KEY (
			ZONE_ID -- 놀이구역ID
		)
		REFERENCES ZONE ( -- 놀이구역
			ID -- ID
		);

-- 놀이구역 -> 놀이구역쾌적도시통계
COMMENT ON CONSTRAINT FK_ZONE_TO_ZONE_AIR_HOUR_STATISTICS ON ZONE_AIR_HOUR_STATISTICS IS '놀이구역 -> 놀이구역쾌적도시통계';