INSERT INTO ZONE_COORDINATE VALUES('A',10,20);
INSERT INTO ZONE_COORDINATE VALUES('A',20,30);
INSERT INTO ZONE_COORDINATE VALUES('A',30,30);
INSERT INTO ZONE_COORDINATE VALUES('A',40,20);
INSERT INTO ZONE_COORDINATE VALUES('A',50,20);
INSERT INTO ZONE_COORDINATE VALUES('A',60,20);

INSERT INTO ZONE_COORDINATE VALUES('B',10,40);
INSERT INTO ZONE_COORDINATE VALUES('B',20,50);
INSERT INTO ZONE_COORDINATE VALUES('B',30,60);
INSERT INTO ZONE_COORDINATE VALUES('B',40,70);
INSERT INTO ZONE_COORDINATE VALUES('B',50,80);
INSERT INTO ZONE_COORDINATE VALUES('B',60,90);