INSERT INTO ZONE VALUES('A','NAMEA',10,3,10,'OK');
INSERT INTO ZONE VALUES('B','NAMEB',10,3,10,'OK');
INSERT INTO ZONE VALUES('C','NAMEC',10,3,10,'OK');
INSERT INTO ZONE VALUES('D','NAMED',10,3,10,'OK');
INSERT INTO ZONE VALUES('E','NAMEE',10,3,10,'OK');