package api;

public enum Status {

   SUCCESS(200,"SUCCESS")   
  ,INSERT_SUCCESS(2001,"INSERT_SUCCESS")
  ,SELECT_SUCCESS(2002,"SELECT_SUCCESS")
  ,UPDATE_SUCCESS(2003,"UPDATE_SUCCESS")
  ,LOGIN_SUCCESS(2004,"LOGIN_SUCCESS")
  ,LOGIN_FAIL(2005,"LOGIN_FAIL")
  
  
  ,FAIL(400,"FAIL")
  ,INSERT_FAIL(4001,"INSERT_FAIL")
  ,SELECT_FAIL(4002,"SELECT_FAIL")
  ,UPDATE_FAIL(4003,"UPDATE_FAIL")
  ,BATCH_FAIL(4004,"BATCH_FAIL")
  
  
  
  
  
  ,DATA_INTEGRITY_VIOLATION_EXCEPTION(3001,"DATA_INTEGRITY_VIOLATION_EXCEPTION") 
  ,PSQL_EXCEPTION(3002,"PSQL_EXCEPTION")
  ,PARSE_EXCEPTION(3003,"PARSE_EXCEPTION")
  ,CALSS_NOT_FOUND_EXCEPTION(3004,"CLASS_NOT_FOUND_EXCEPTION")
  ,NO_SUCH_METHOD_EXCEPTION(3005,"NO_SUCH_METHOD_EXCEPTION")
  ,SCHEDULER_EXCEPTION(3006,"SCHEDULER_EXCEPTION")
  ,SQL_EXCEPTION(3007,"SQL_EXCEPTION")
  ,JSON_PROCESSING_EXCEPTION(3008,"JSON_PROCESSING_EXCEPTION")
  ,IOEXCEPTION(3008,"IOEXCEPTION")
  ,SET_STATISTICS_DATA_ERROR(3008,"SET_STATISTICS_DATA_ERROR")
  ,UNKNOWN_DEVICE_ID(3008,"UNKNOWN_DEVICE_ID")
  ,BATCH_TYPE_EXCEPTION(3009,"BATCH_TYPE_EXCEPTION")
  
  ,UNKNOWN_EXCEPTION(3999,"EXCEPTION")
  
  ,ALREADY_RENT_DEVICE(4000,"ALREADY_RENT_DEVICE")
  
  
  
  ,EMPTY_LIST(5000,"EMPTY_LIST")
  ;
  
  
  
  private final int codeName;
  private final String detail;

  private Status(int code, String detailStr) {
    this.codeName = code;
    this.detail = detailStr;
  }

  public int getCode() {
    return codeName;
  }
  
  public String getDetail() {
    return detail;    
  }
}
